name: Compile
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf
  build_html:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - uses: docker://pandoc/core:2.9
        with:
          args: "main.tex -f latex -t html --css pandoc.css --self-contained -s -o index.html"
      - uses: actions/upload-artifact@master
        with:
          name: HTML
          path: index.html
  deploy:
    runs-on: ubuntu-latest
    needs: [build_latex, build_html]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Copy files
        run: |
          ls -la
          ls -la PDF
          ls -la HTML
          mkdir public
          cp PDF/main.pdf public/main.pdf
          cp HTML/index.html public/index.html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
